# Job template: Deactivate all non-latest active versions
parameters:
  - name: artifactName
    type: string
    default: 'sbom-files'
  - name: tryDownloadArtifact
    type: boolean
    default: true
  - name: dependsOn
    type: object
    default: []
  - name: condition
    type: string
    default: succeeded()

jobs:
  - job: deactivate_old_versions
    displayName: "Set non-latest versions to inactive"
    dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}
    steps:
      - template: /src/security/dependency-track/steps/deactivate-nonlatest.steps.yaml@templates
        parameters:
          artifactName: ${{ parameters.artifactName }}
          tryDownloadArtifact: ${{ parameters.tryDownloadArtifact }}
