# Job template: Deactivate all non-latest active versions (optionally scoping by env tag)
parameters:
  - name: artifactName
    type: string
    default: 'sbom-files'
  - name: tryDownloadArtifact
    type: boolean
    default: true

jobs:
  - job: deactivate_old_versions
    displayName: "Set non-latest versions to inactive"
    steps:
      - template: /src/security/dependency-track/steps/deactivate-nonlatest.steps.yaml@templates
        parameters:
          artifactName: ${{ parameters.artifactName }}
          tryDownloadArtifact: ${{ parameters.tryDownloadArtifact }}
