# Job template: Generate SBOMs (npm + .NET) and export sbomReady as a job output
parameters:
  # Paths or multi-line lists you want to pass through to the steps template
  - name: dotnetProjectsMultiline
    type: string
    default: ''
  - name: npmRootsMultiline
    type: string
    default: ''
  # Controls passed to the steps template
  - name: publishArtifact
    type: boolean
    default: true
  - name: artifactName
    type: string
    default: 'sbom-files'
  - name: outputFormat
    type: string
    default: 'cyclonedx-json'
  - name: nodeVersion
    type: string
    default: '20.x'
  - name: includeLicenseTexts
    type: boolean
    default: true

jobs:
  - job: generate_sbom
    displayName: "Generate SBOMs & publish artifact"
    steps:
      - template: /src/security/dependency-track/steps/generate-sbom.steps.yaml@templates
        parameters:
          dotnetProjectsMultiline: |
            ${{ parameters.dotnetProjectsMultiline }}
          npmRootsMultiline: |
            ${{ parameters.npmRootsMultiline }}
          publishArtifact: ${{ parameters.publishArtifact }}
          artifactName: ${{ parameters.artifactName }}
          outputFormat: ${{ parameters.outputFormat }}
          nodeVersion: ${{ parameters.nodeVersion }}
          includeLicenseTexts: ${{ parameters.includeLicenseTexts }}

      # Promote the in-job variable `sbomExists` to a **stage output** we can consume later
      - pwsh: |
          Write-Host "sbomExists=$(sbomExists)"
          if ('$(sbomExists)' -eq 'true') {
            Write-Host "##vso[task.setvariable variable=sbomReady;isOutput=true]true"
          } else {
            Write-Host "##vso[task.setvariable variable=sbomReady;isOutput=true]false"
          }
        name: exportSbomReady
        displayName: "Export SBOM readiness as stage output"
