parameters:
  - name: runNpm
    type: boolean
    default: 'true'
  - name: runDotnet
    type: boolean
    default: 'true'
  - name: npmSbomOutputFormat
    type: string
    default: 'cyclonedx-json'   # (Other options per Syft: spdx-json, json, table, etc.)
  - name: dotnetSbomOutputFormat
    type: string
    default: 'cyclonedx-json'
  - name: npmScanDirectory
    type: string
    default: '$(System.DefaultWorkingDirectory)/src/apps'
  - name: dotnetScanDirectory
    type: string
    default: '$(Pipeline.Workspace)/$(Build.DefinitionName)'
  - name: outputFolder
    type: string
    default: '$(Agent.TempDirectory)\sbom'
  - name: artifactName
    type: string
    default: 'sbom-files'
  - name: syftInstallUrl
    type: string
    default: 'https://raw.githubusercontent.com/anchore/syft/main/install.sh'

jobs:
  - job: GenerateSBOM
    displayName: 'Generate SBOM'
    steps:
      - download: current
        displayName: 'Download Source Code'

      - script: mkdir "${{ parameters.outputFolder }}"
        displayName: 'Create SBOM Folder'

      - script: |
          curl -sSfL ${{ parameters.syftInstallUrl }} | sh -s -- -b $(Agent.TempDirectory)
        displayName: 'Install Syft (SBOM Generator)'
      
      # Generate the NPM SBOM if enabled.
      - ${{ if eq(parameters.runNpm, true) }}:
          - script: |
              "$(Agent.TempDirectory)\syft.exe" -o ${{ parameters.npmSbomOutputFormat }}="${{ parameters.outputFolder }}\sbom-npm-file.json" "${{ parameters.npmScanDirectory }}"
            displayName: 'Generate NPM SBOM'
      
      # Generate the .NET SBOM if enabled.
      - ${{ if eq(parameters.runDotnet, true) }}:
          - script: |
              "$(Agent.TempDirectory)\syft.exe" -o ${{ parameters.dotnetSbomOutputFormat }}="${{ parameters.outputFolder }}\sbom-dotnet-file.json" "${{ parameters.dotnetScanDirectory }}"
            displayName: 'Generate .NET SBOM'

      - task: PublishPipelineArtifact@1
        displayName: 'Publish SBOM Output'
        inputs:
          targetPath: ${{ parameters.outputFolder }}
          publishLocation: 'pipeline'
          artifact: ${{ parameters.artifactName }}
