parameters:
  # Object containing parameter overrides for the sbom-generation.yaml template.
  - name: generation
    type: object
    default: {}   # Example: { runDotnet: false, npmScanDirectory: '$(Build.SourcesDirectory)/my-npm-app' }

  # Object containing parameter overrides for the sbom-analysis.yaml template.
  - name: analysis
    type: object
    default: {}   # Example: { runDotnet: false, downloadArtifact: true }

jobs:
  - template: sbom-generation.yaml
    parameters: ${{ parameters.generation }}

  - template: sbom-analysis.yaml
    parameters: ${{ parameters.analysis }}
    dependsOn: GenerateSBOM