# Task to add a variable to the Terraform tfvars file
# This YAML script is used in an Azure DevOps pipeline to dynamically append a variable
# (name and value) to a Terraform tfvars file. It ensures proper handling of Boolean values
# by normalizing them to lowercase without quotes, as required by Terraform. 
# All other values are added as strings, wrapped in quotes, maintaining compatibility with Terraform.

parameters:
  # The directory where the Terraform tfvars file is located. Defaults to the pipeline's working directory.
  - name: terraformDirectory
    default: '$(System.DefaultWorkingDirectory)'
  # The name of the variable to be added to the tfvars file. This should not be empty.
  - name: variableName
    default: ''

  # The value of the variable to be added to the tfvars file. It can be a string, a number, or a Boolean.
  - name: variableValue
    default: ''
    
steps:
  - task: Powershell@2
    displayName: Set Terraform Variable '${{ parameters.variableName }}'
    inputs:
      targetType: inline
      script: |
        $name = "${{parameters.variableName}}"
        
        # Validate that the variable name is not empty
        if ($name.Length -lt 1) {
          echo "Variable name is missing."
          exit 1
        }
        
        # Get the raw value of the variable
        $rawValue = "${{parameters.variableValue}}"
        
        # Add quotes to the raw value
        $value = "`"$rawValue`""
        
        # Check if the value is a Boolean and normalize it to lowercase if true
        if ($rawValue -ieq "true" -or $rawValue -ieq "false") {
          # Normalize Boolean to lowercase
          $value = $rawValue.ToLower()
        }
        
        # Add the variable to the tfvars file
        Add-Content ${{parameters.terraformDirectory}}/terraform.tfvars "`n`t$name = $value"
        
        Write-Host "$name is $value"
        
        exit 0
