# Job to deploy a NuGet Package to the Internal Public Feed
jobs:
  - deployment: Job_Deploy
    displayName: Deploy to NuGet (Internal Public)
    environment: NuGet Internal (Gated)
    strategy:
      runOnce:
        deploy:
          steps:
            - task: NuGetToolInstaller@1
              displayName: Get NuGet

            - task: NuGetCommand@2
              displayName: NuGet Push
              inputs:
                command: 'push'
                packagesToPush: '$(Pipeline.Workspace)\**\*.nupkg'
                nuGetFeedType: 'internal'
                publishVstsFeed: 'Audacia.Public/AudaciaPublic'