# Job to deploy a NuGet Package to the Public NuGet Feed
parameters:
  - name: trustedSigningEndpoint
    type: string
  - name: trustedSigningAccount
    type: string
  - name: trustedSigningCertificateProfile
    type: string

jobs:
  - deployment: Job_Deploy
    displayName: Deploy to NuGet (Public)
    environment: NuGet Public
    pool:
      vmImage: windows-latest
    strategy:
      runOnce:
        deploy:
          steps:
            - task: PowerShell@2
              displayName: NuGet Sign
              inputs:
                targetType: inline
                pwsh: true
                script: |
                  dotnet tool install Knapcode.CertificateExtractor --global
                  dotnet tool install sign --global --prerelease
                  $packagesToSign = Get-ChildItem -Path "$(Pipeline.Workspace)" -Filter "*.nupkg" -Recurse
                  foreach ($package in $packagesToSign) {
                      $path = $package.FullName
                      sign code trusted-signing "$path" -tse "${{ parameters.trustedSigningEndpoint }}" -tsa "${{ parameters.trustedSigningAccount }}" -tscp "${{ parameters.trustedSigningCertificateProfile }}"
                  }
                  # All packages will be signed with the same certificate, so only need to extract one
                  nuget-cert-extractor --file "$path" --output "$(Build.ArtifactsStagingDirectory)" --code-signing --author --leaf

            - task: PublishPipelineArtifact@1
              inputs:
                targetPath: $(Build.ArtifactsStagingDirectory)/*.cer
                artifactName: PackageSigningCertificate

            - task: ManualValidation@0
              inputs:
                instructions: 'Upload the certificate published as an artifact in the previous step to the Audacia organization on nuget.org'
                timeoutInMinutes: 2880 # 2 day timeout, as certificates expire
                onTimeout: reject

            - task: NuGetToolInstaller@1
              displayName: Use NuGet

            - task: NuGetCommand@2
              displayName: NuGet Push
              inputs:
                command: 'push'
                packagesToPush: '$(Pipeline.Workspace)\**\*.nupkg'
                nuGetFeedType: 'external'
                publishFeedCredentials: 'Public NuGet'