# Job to deploy a NuGet Package to the Public NuGet Feed
jobs:
  - job: Job_Pause
    displayName: Wait for NuGet Certificate Upload
    pool: server
    steps:
      # Need to pause as trusted signing certificates are rotated every few days, so we need to ensure the signing certificate has been uploaded to nuget.org
      - task: ManualValidation@1
        inputs:
          notifyUsers: ''
          instructions: 'Ensure the signing certificate published as an artifact in the previous stage has been uploaded to nuget.org'
          timeoutInMinutes: 2880 # 2 day timeout, as certificates expire
          onTimeout: reject

  - deployment: Job_Deploy
    displayName: Deploy to NuGet (Public)
    dependsOn: Job_Pause
    environment: NuGet Public
    strategy:
      runOnce:
        deploy:
          steps:
            - task: NuGetToolInstaller@1
              displayName: Use NuGet

            - task: NuGetCommand@2
              displayName: NuGet Push
              inputs:
                command: 'push'
                packagesToPush: '$(Pipeline.Workspace)\**\*.nupkg'
                nuGetFeedType: 'external'
                publishFeedCredentials: 'Public NuGet'