# Job to deploy a NuGet Package to the Public NuGet Feed
jobs:
  - deployment: Job_Deploy
    displayName: Deploy to NuGet (Public)
    environment: NuGet Public
    strategy:
      runOnce:
        deploy:
          steps:
            - task: NuGetToolInstaller@1
              displayName: Use NuGet

            - task: NuGetCommand@2
              displayName: NuGet Push
              inputs:
                command: 'push'
                packagesToPush: '$(Pipeline.Workspace)\**\*.nupkg'
                nuGetFeedType: 'external'
                publishFeedCredentials: 'Public NuGet'