parameters:
  - name: serviceConnectionName # The name of the service connection used to deploy to Azure
    type: string
  - name: slotName # The name of the slot to deploy to, that will be swapped into production
    default: 'Staging'
  - name: resourceGroupName # The name of the resource group the app services are in
    type: string
  - name: appServices # The names of the app services to swap the slots in
    default: []
    type: object
  - name: ignoreEmptyAppServices
    type: boolean
    default: false

steps:
  - task: AzureCLI@2
    displayName: 'Swap Slots'
    inputs:
      azureSubscription: ${{parameters.serviceConnectionName}}
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        $ResourceNames = '${{convertToJson(parameters.appServices)}}' | ConvertFrom-Json;
        # only drop empty entries when requested
        $ignoreEmpty = ${{ parameters.ignoreEmptyAppServices }}
        if ($ignoreEmpty) {
        $ResourceNames = $ResourceNames | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }
        }

        $ResourceGroupName = '${{parameters.resourceGroupName}}'
        $slotName = '${{parameters.slotName}}'
        $slotSwapCompleted = [System.Collections.Concurrent.ConcurrentBag[string]]::new()
        $slotSwapErrored = [System.Collections.Concurrent.ConcurrentBag[string]]::new()

        $ResourceNames | ForEach-Object -Parallel {
            $target = $_
            try {
                Write-Host "Starting swap for $target"
                az webapp deployment slot swap -g $using:ResourceGroupName -n $target --slot $using:slotName --target-slot production | ConvertFrom-Json
        
                if (!$?) 
                {
                    throw "Swap failed for $target"            
                } 
                else 
                {
                    ($using:slotSwapCompleted).Add($target)
                    Write-Host "Completed swap for $target successfully"
                }
            } 
            catch 
            {
                Write-Host "Exception during swap for $($target): $_"
                ($using:slotSwapErrored).Add($target)
            }
        }

        Write-Host "Slots swapped successfully: $($slotSwapCompleted.Count)"
        Write-Host "Slot swap errors: $($slotSwapErrored.Count)"

        if($slotSwapErrored.Count -gt 0)
        {
            $slotSwapCompleted | ForEach-Object {
                $target = $_
                Write-Host "Reversing slot swap for $target"
                az webapp deployment slot swap -g $ResourceGroupName -n $target --slot $slotName --target-slot production | ConvertFrom-Json
            }
            exit 1
        } 
        else 
        {
            exit 0
        }