# Task to adds/updates variables in an Azure Key Vault
parameters:
  - name: keyVaultName # The name of the key vault
    type: string
    default: ''
  - name: variables # Array of objects with variableName, variableValue
    type: object
    default: []
  - name: serviceConnectionName # The name of the service connection to connect to Azure with.
    type: string
    default: ''

steps:
  - task: AzureCLI@2
    displayName: 'Save ${{parameters.keyVaultName}} variables'
    inputs:
      azureSubscription: ${{parameters.serviceConnectionName}}
      scriptType: ps
      scriptLocation: 'inlineScript'
      inlineScript: |
        $keyVaultName = "${{parameters.keyVaultName}}";

        # Convert variables array passed from the parameters to a powershell object
        $variables = '${{convertToJson(parameters.variables)}}' | ConvertFrom-Json;

        # Iterate over each variable and add it to the key vault
        foreach ($var in $variables) {
          $varName = $var.variableName;
          $varValue = '"{0}"' -f $($var.variableValue -replace '"', '""');

          Write-Host "Adding/Updating variable '$varName'.";

          $res = az keyvault secret set `
            --name $varName `
            --vault-name $keyVaultName `
            --value $varValue;
        }